CREATE TABLE IF NOT EXISTS "users" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  uuid VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "lessons" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_uuid VARCHAR(255) NOT NULL,
  video_url VARCHAR(255),
  likes INT DEFAULT 0,
  FOREIGN KEY(user_uuid) REFERENCES "users"("uuid")
);
